//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources.Inschrijvingen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources.Inschrijvingen.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorieën.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        public static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestigen.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verantwoordelijke.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn deelnemers.
        /// </summary>
        public static string MyParticipants {
            get {
                return ResourceManager.GetString("MyParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volgende.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen deelnemers.
        /// </summary>
        public static string NoParticipants {
            get {
                return ResourceManager.GetString("NoParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen deelnemers die in aanmerking komen voor dit tornooi. U kan deelnemers toevoegen in uw account..
        /// </summary>
        public static string NoParticipantsText {
            get {
                return ResourceManager.GetString("NoParticipantsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deelnemers.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betalingsinformatie.
        /// </summary>
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uiterste inschrijving.
        /// </summary>
        public static string RegistrationDeadline {
            get {
                return ResourceManager.GetString("RegistrationDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inschrijvingsgeld.
        /// </summary>
        public static string RegistrationFee {
            get {
                return ResourceManager.GetString("RegistrationFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer Deelnemers.
        /// </summary>
        public static string SelectParticipants {
            get {
                return ResourceManager.GetString("SelectParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer deelnemers voor dit tornooi.
        /// </summary>
        public static string SelectParticipantsForThisTournament {
            get {
                return ResourceManager.GetString("SelectParticipantsForThisTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer Tornooi.
        /// </summary>
        public static string SelectTournament {
            get {
                return ResourceManager.GetString("SelectTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tornooi.
        /// </summary>
        public static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
    }
}
