//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources.Account.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ander land toevoegen.
        /// </summary>
        public static string AddOtherCountry {
            get {
                return ResourceManager.GetString("AddOtherCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een email voor bevestiging is verzonden naar.
        /// </summary>
        public static string AnEmailForConfirmationIsSentTo {
            get {
                return ResourceManager.GetString("AnEmailForConfirmationIsSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controleer uw email en bevestig uw account, u moet bevestigd hebben voor u kan inloggen..
        /// </summary>
        public static string CheckEmailText {
            get {
                return ResourceManager.GetString("CheckEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        public static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubnaam.
        /// </summary>
        public static string ClubName {
            get {
                return ResourceManager.GetString("ClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubnummer.
        /// </summary>
        public static string ClubNumber {
            get {
                return ResourceManager.GetString("ClubNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De clubnummer in dit land bestaat al.
        /// </summary>
        public static string ClubNumberExistsInCountry {
            get {
                return ResourceManager.GetString("ClubNumberExistsInCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig uw account-Resend.
        /// </summary>
        public static string ConfirmAccountResend {
            get {
                return ResourceManager.GetString("ConfirmAccountResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U hebt een bevestigd email adres nodig om in te loggen..
        /// </summary>
        public static string ConfirmedEmailError {
            get {
                return ResourceManager.GetString("ConfirmedEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig Email.
        /// </summary>
        public static string ConfirmEmailTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig wachtwoord.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig uw account.
        /// </summary>
        public static string ConfirmYourAccount {
            get {
                return ResourceManager.GetString("ConfirmYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve uw account te bevestigen door.
        /// </summary>
        public static string ConfirmYourAccountText {
            get {
                return ResourceManager.GetString("ConfirmYourAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hier.
        /// </summary>
        public static string ConfirmYourAccountText2 {
            get {
                return ResourceManager.GetString("ConfirmYourAccountText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to te klikken.
        /// </summary>
        public static string ConfirmYourAccountText3 {
            get {
                return ResourceManager.GetString("ConfirmYourAccountText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een nieuwe account aan..
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        public static string EmailLink {
            get {
                return ResourceManager.GetString("EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email = Login.
        /// </summary>
        public static string EmailLogin {
            get {
                return ResourceManager.GetString("EmailLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voer een email adres in.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord vergeten bevestiging.
        /// </summary>
        public static string ForgotPassConf {
            get {
                return ResourceManager.GetString("ForgotPassConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord vergeten?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldige code..
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldige login poging..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familienaam.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmelden.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verantwoordelijke.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huisnummer.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wachtwoord en bevestigend wachtwoord komen niet overeen.
        /// </summary>
        public static string PassAndConfPassNoMatch {
            get {
                return ResourceManager.GetString("PassAndConfPassNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve uw email te controleren om uw wachtwoord te opnieuw in te stellen..
        /// </summary>
        public static string PleaseCheckEmailToResetPass {
            get {
                return ResourceManager.GetString("PleaseCheckEmailToResetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreer.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreer als nieuwe gebruiker.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onthoud deze browser?.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onthoud mij?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord opnieuw instellen bevestiging.
        /// </summary>
        public static string ResetPassConf {
            get {
                return ResourceManager.GetString("ResetPassConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord opnieuw instellen.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve uw wachtwoord opnieuw in te stellen door.
        /// </summary>
        public static string ResetPasswordText {
            get {
                return ResourceManager.GetString("ResetPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hier.
        /// </summary>
        public static string ResetPasswordText2 {
            get {
                return ResourceManager.GetString("ResetPasswordText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to te klikken.
        /// </summary>
        public static string ResetPasswordText3 {
            get {
                return ResourceManager.GetString("ResetPasswordText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stel uw wachtwoord opnieuw in..
        /// </summary>
        public static string ResetYourPassword {
            get {
                return ResourceManager.GetString("ResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straat.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het {0} moet minstens {2} karakters lang zijn..
        /// </summary>
        public static string StringLengthError {
            get {
                return ResourceManager.GetString("StringLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dank u voor het bevestigen van uw email..
        /// </summary>
        public static string ThankConfEmail {
            get {
                return ResourceManager.GetString("ThankConfEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hier te klikken om in te loggen.
        /// </summary>
        public static string ThankConfEmailClickHere {
            get {
                return ResourceManager.GetString("ThankConfEmailClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve.
        /// </summary>
        public static string ThankConfEmailPlease {
            get {
                return ResourceManager.GetString("ThankConfEmailPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik een locale account om aan te melden..
        /// </summary>
        public static string UseLocalAccountToLogIn {
            get {
                return ResourceManager.GetString("UseLocalAccountToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw wachtwoord is opnieuw ingesteld..
        /// </summary>
        public static string YourPassHasBeenReset {
            get {
                return ResourceManager.GetString("YourPassHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hier te klikken om in te loggen.
        /// </summary>
        public static string YourPassHasBeenResetClick {
            get {
                return ResourceManager.GetString("YourPassHasBeenResetClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve.
        /// </summary>
        public static string YourPassHasBeenResetPlease {
            get {
                return ResourceManager.GetString("YourPassHasBeenResetPlease", resourceCulture);
            }
        }
    }
}
